# IB 2ND Grade Averag
period_1 = int(input("hey what is your grade in your first period Grade:\n "))
period_2 = int(input("what is your grade in second period Grade:\n "))
period_3 = int(input("what is your grade in third period?:\n "))
period_4 = int(input("My grade is ok with this clas so what is your grade in fourth period:\n "))
period_5 = int(input("What is your grade in your 5th period class?:\n "))
period_6 = int(input("what is youe grade in sixth period:\n "))
period_7 = int(input("what is your grade in your seventh period:\n "))
grade_avarge = float( "period_1 = period_2 = period_3 = period_4 = period_5 = period_6 = period_7"/5)
grade_avarge = round((grade_avarge)/2)
print("your grade average is", grade_avarge )