# Ib 2nd madlib
print("madlib")
verb_one = input("Can you give me a verb: ")
noun_one = input("Give me a noun: ")
adverb = input("please give me a adverb; ")
verb_past = input("can you give me a past tense verb; ")
pluaral_noun1 = input("please give me a pluaral noun: ")
pluaral_noun2 = input("Give me another differnet pluaral noun: ")
adjective = input("can you giveme a adjective: ")
pluaral_noun3 = input("give me a different pluaral noun different from the other two: ")
verb_ing = input("type a verd that ends with ing: ")
color = input("give me a color: ")
pluaral_noun4 = input("give me a new pluaral noun: ")
noun_two = input("pease give me a another noun: ")
noun_three = input("can you give me another noun difernet from the other two: ")
interjectrion = input("Can you please give me a interjectrion: ")
adjective_2 = input("please give me another different adjective: ")
verb_2 = input("can you give me a different verb: ")
adjective_3 = input ("please give me a different adjective: ")
adjective_4 =input("give me the last adjective: ")
print("O say can you"+ verb_one, "by the dawn's early"+ noun_one,"What so"+ adverb, "we"+ verb_past, "at the twilight's last gleaming, Whose broad"+ pluaral_noun1, "and bright"+pluaral_noun2,"through the"+adjective,"fight, O'er the"+pluaral_noun3,"we watched,were so gallantly"+verb_ing,"And the rocket's"+color,"glare, the"+pluaral_noun4,"burstiong in"+noun_two,"Gave proof through the night that our"+noun_three, "was still there;"+interjectrion,"does that"+adjective_2,"banner yet"+verb_2,"O'er the land of the"+adjective_3, "and the home of the"+adjective_4,"?" )