# I'ini Bohnet madlib
print("madlib")
man = input("Can you give me a name of a man: ").strip().title()
woman = input("Give me a name of a woman: ").strip().title()
adverb = input("please give me a adverb: ").strip().lower()
noun_two = input("pease give me a another noun: ").strip().lower()
noun_three = input("can you give me another noun that is differnet: ").strip().lower()
adjective = input("can you giveme a adjective: ").strip().lower()
noun_four = input("pease give me a different noun: ").strip().lower()
noun_five = input("pease give me a another noun that is different; ").strip().lower()
adjective_2 = input("please give me another different adjective: ").strip().lower()
place = input("can you give a name of a place: ").strip().lower()
verb_past = input("can you give me a past tense verb: ").strip().lower()
number = input("can you give me a number: ").strip().lower()
adjective_3 = input("can you give me another adjective: ").strip().lower()
body_part = input("give me a random body part: ").strip().lower()
wbody_part = input("can you give me another body part: ").strip().lower()
adjective_4 = input("can you give me a different adjective: ").strip().lower()
adjective_5 = input("can you give me another adjective: ").strip().lower()
verb_1 = input("Can you give me a verb?: ").strip().lower()
verb_2 = input("Can you give me give me another verb: ").strip().lower()
verb_3 = input("Can you give me a different verb: ").strip().lower()
verb_4 = input("Can you give me a verb that you haven't given me yet: ").strip().lower()
noun_four = input("can you give me another noun: ").strip().lower()
verb_5 = input("can you give me another verb: ").strip().lower()
noun_five = input("can you give me another noun: ").strip().lower()
print(f"Once upon a time {man} and {woman} fell in love. {man} adored {woman}'s {noun_two} and {woman} loved {man}'s {noun_three}. Their wedding was {adjective}. Everyone enjoyed the {noun_four} and {noun_five}. after the wedding they had a {adjective_2} honeymoon. Where they traveled to {place} and {verb_past} with each other daily. They had a child {number} months later. This {adjective_3} child had {man}'s {body_part} and {woman}'s {wbody_part}. Through the many years after their marriage continued to be {adjective_4} thanks to the {adjective_5} advice that they received on their wedding day. Don't forget to {verb_1} each other and always {verb_2} after you {verb_3}. {man} always {verb_4} {woman}'s {noun_four} and {woman} you should always {verb_5} {man}'s {noun_five}. And they lived happily ever after")